-- MySQL Script generated by MySQL Workbench
-- sex 15 mai 2026 14:23:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `banco` ;

-- -----------------------------------------------------
-- Table `banco`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(255) NOT NULL,
  `emailUsuario` VARCHAR(255) NOT NULL,
  `dataNascimentoUsuario` DATE NULL DEFAULT NULL,
  `cpfUsuario` CHAR(11) NULL DEFAULT NULL,
  `usernameUsuario` VARCHAR(255) NOT NULL,
  `senhaUsuario` VARCHAR(255) NOT NULL,
  `dataCriacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `municipio_codigo` INT NOT NULL,
  `fotoUsuario` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `emailUsuario` (`emailUsuario` ASC) VISIBLE,
  UNIQUE INDEX `usernameUsuario` (`usernameUsuario` ASC) VISIBLE,
  UNIQUE INDEX `cpfUsuario` (`cpfUsuario` ASC) VISIBLE,
  INDEX `fk_usuarios_municipio1_idx` (`municipio_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_municipio1`
    FOREIGN KEY (`municipio_codigo`)
    REFERENCES `banco`.`municipio` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banco`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(255) NOT NULL,
  `descricaoProduto` TEXT NULL DEFAULT NULL,
  `precoProduto` DECIMAL(10,2) NOT NULL,
  `statusProduto` VARCHAR(50) NULL DEFAULT NULL,
  `dataPublicacaoProduto` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_idUsuario` INT NULL DEFAULT NULL,
  `fotoProduto` VARCHAR(255) NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `usuario_idUsuario` (`usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `produtos_ibfk_1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `banco`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banco`.`avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`avaliacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL DEFAULT NULL,
  `idProduto` INT NULL DEFAULT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `nota` INT NULL DEFAULT NULL,
  `dataAvaliacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  INDEX `idProduto` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `avaliacoes_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `banco`.`usuarios` (`idUsuario`),
  CONSTRAINT `avaliacoes_ibfk_2`
    FOREIGN KEY (`idProduto`)
    REFERENCES `banco`.`produtos` (`idProduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banco`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigoUf` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `regiao` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banco`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`favoritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsuario` (`idUsuario` ASC, `idProduto` ASC) VISIBLE,
  INDEX `idProduto` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `favoritos_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `banco`.`usuarios` (`idUsuario`),
  CONSTRAINT `favoritos_ibfk_2`
    FOREIGN KEY (`idProduto`)
    REFERENCES `banco`.`produtos` (`idProduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banco`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`municipios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `estados_id` INT NOT NULL,
  `usuarios_idUsuario` INT NOT NULL,
  `usuarios_estado_codigoUf` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_idUsuario`, `usuarios_estado_codigoUf`),
  INDEX `fk_municipios_estados1_idx` (`estados_id` ASC) VISIBLE,
  INDEX `fk_municipios_usuarios1_idx` (`usuarios_idUsuario` ASC, `usuarios_estado_codigoUf` ASC) VISIBLE,
  CONSTRAINT `fk_municipios_estados1`
    FOREIGN KEY (`estados_id`)
    REFERENCES `banco`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_municipios_usuarios1`
    FOREIGN KEY (`usuarios_idUsuario`)
    REFERENCES `banco`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
