-- MySQL Script generated by MySQL Workbench
-- qui 16 abr 2026 15:27:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `banco` ;

-- -----------------------------------------------------
-- Table `banco`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`estado` (
  `codigo_uf` INT NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `latitude` DECIMAL(10,6) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,6) NULL DEFAULT NULL,
  `regiao` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_uf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banco`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`municipio` (
  `codigo_ibge` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `latitude` DECIMAL(10,6) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,6) NULL DEFAULT NULL,
  `capital` TINYINT(1) NULL DEFAULT NULL,
  `codigo_uf` INT NULL DEFAULT NULL,
  `siafi_id` INT NULL DEFAULT NULL,
  `ddd` INT NULL DEFAULT NULL,
  `fuso_horario` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_ibge`),
  INDEX `codigo_uf` (`codigo_uf` ASC) VISIBLE,
  CONSTRAINT `municipio_ibfk_1`
    FOREIGN KEY (`codigo_uf`)
    REFERENCES `banco`.`estado` (`codigo_uf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banco`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(255) NOT NULL,
  `emailUsuario` VARCHAR(255) NOT NULL,
  `dataNascimentoUsuario` DATE NULL DEFAULT NULL,
  `cpfUsuario` CHAR(11) NULL DEFAULT NULL,
  `usernameUsuario` VARCHAR(255) NOT NULL,
  `senhaUsuario` VARCHAR(255) NOT NULL,
  `dataCriacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `estado_codigo_uf` INT NOT NULL,
  `municipio_codigo_ibge` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `estado_codigo_uf`),
  UNIQUE INDEX `emailUsuario` (`emailUsuario` ASC) VISIBLE,
  UNIQUE INDEX `usernameUsuario` (`usernameUsuario` ASC) VISIBLE,
  UNIQUE INDEX `cpfUsuario` (`cpfUsuario` ASC) VISIBLE,
  INDEX `fk_usuarios_municipio1_idx` (`municipio_codigo_ibge` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_municipio1`
    FOREIGN KEY (`municipio_codigo_ibge`)
    REFERENCES `banco`.`municipio` (`codigo_ibge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banco`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(255) NOT NULL,
  `descricaoProduto` TEXT NULL DEFAULT NULL,
  `precoProduto` DECIMAL(10,2) NOT NULL,
  `statusProduto` VARCHAR(50) NULL DEFAULT NULL,
  `dataPublicacaoProduto` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_idUsuario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `usuario_idUsuario` (`usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `produtos_ibfk_1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `banco`.`usuarios` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banco`.`avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`avaliacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NULL DEFAULT NULL,
  `idProduto` INT NULL DEFAULT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `nota` INT NULL DEFAULT NULL,
  `dataAvaliacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  INDEX `idProduto` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `avaliacoes_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `banco`.`usuarios` (`idUsuario`),
  CONSTRAINT `avaliacoes_ibfk_2`
    FOREIGN KEY (`idProduto`)
    REFERENCES `banco`.`produtos` (`idProduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table `banco`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`favoritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idProduto` INT NOT NULL,
  `dataFavorito` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsuario` (`idUsuario` ASC, `idProduto` ASC) VISIBLE,
  INDEX `idProduto` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `favoritos_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `banco`.`usuarios` (`idUsuario`),
  CONSTRAINT `favoritos_ibfk_2`
    FOREIGN KEY (`idProduto`)
    REFERENCES `banco`.`produtos` (`idProduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
